import os

WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500
INPUT_MATRIX_WIDTH = 1000
INPUT_MATRIX_HEIGHT = 700
PATH_DIRECTORY = os.path.dirname(__file__)
PATH_IMAGES = os.path.join(PATH_DIRECTORY,'images')
PATH_THEME = os.path.join(PATH_DIRECTORY,'theme')